import json
import pathlib

corpus = [
{"id":"fto_dm2_scandinavian","titulo":"FTO rs9939609 e risco de diabetes tipo 2 (meta-analise escandinava)","fonte":"Meta-analise de coortes escandinavas (n=41.504)","eixo":"fit-doencas","gene":"FTO","rsid":"rs9939609","evidencia":"forte","texto":"O alelo de risco do polimorfismo rs9939609 no gene FTO associa-se ao diabetes tipo 2 com odds ratio de aproximadamente 1,13. A associacao com diabetes incidente mantem odds ratio em torno de 1,16. Um achado central e que a associacao permanece estatisticamente significativa mesmo apos correcao para o indice de massa corporal, indicando que o FTO influencia o risco de diabetes em parte de forma independente do seu efeito sobre o peso corporal. Conecta o painel Fit (predisposicao a IMC elevado e obesidade) ao painel de doencas (risco de diabetes tipo 2)."},
{"id":"fto_dm2_indian","titulo":"FTO e diabetes tipo 2 em populacao indiana","fonte":"Meta-analise em populacao indiana (n=28.394)","eixo":"fit-doencas","gene":"FTO","rsid":"rs9939609","evidencia":"forte","texto":"Estudo de meta-analise em populacao indiana confirma a associacao entre variantes do gene FTO e risco aumentado de diabetes tipo 2, reforcando a generalidade do conector FTO para diabetes alem de populacoes europeias. Reforca a robustez do conector entre predisposicao a obesidade e risco metabolico."},
{"id":"fto_brasil_obesidade","titulo":"FTO rs9939609 em obesidade severa na populacao brasileira","fonte":"Estudo brasileiro de obesidade severa","eixo":"fit-doencas","gene":"FTO","rsid":"rs9939609","evidencia":"moderada","texto":"Estudo conduzido em populacao brasileira investigou o polimorfismo FTO rs9939609 em individuos com obesidade severa, fornecendo fundamentacao nacional para o uso do marcador FTO no contexto brasileiro. Relevante por ancorar o conector FTO em dados nacionais, ainda que a transferibilidade de pesos derivados de populacoes europeias para a populacao brasileira miscigenada seja uma limitacao reconhecida."},
{"id":"fto_dieta_interacao","titulo":"Interacao FTO x dieta mediterranea no risco de diabetes","fonte":"Estudo de interacao gene-dieta","eixo":"fit-nutri","gene":"FTO","rsid":"rs9939609","evidencia":"moderada","texto":"A associacao do FTO rs9939609 com diabetes tipo 2 e modulada pela dieta: o efeito do alelo de risco e maior quando a adesao a dieta mediterranea e baixa, e atenuado quando a adesao e alta. Sugere que fatores de estilo de vida interagem com a predisposicao genetica. Conecta o painel Fit/FTO ao painel Nutri (eficacia de dietas)."},
{"id":"hrr_nejm","titulo":"Recuperacao da frequencia cardiaca pos-exercicio como preditor de mortalidade","fonte":"NEJM (1999)","eixo":"fit-doencas","gene":"CHRM2","rsid":"rs324640","evidencia":"forte-fenotipo","texto":"Uma recuperacao atenuada da frequencia cardiaca no primeiro minuto apos o exercicio e um forte preditor de mortalidade por todas as causas, independente da carga de trabalho atingida, da presenca de defeitos de perfusao miocardica e das variacoes de frequencia cardiaca durante o exercicio. Importante: este estudo mede o fenotipo (recuperacao observada), nao o genotipo. A ponte entre o marcador genetico CHRM2 rs324640 (predisposicao) e este fenotipo e mais fraca; o conector CHRM2 deve ser apresentado como brando."},
{"id":"hrr_cleveland","titulo":"Recuperacao cardiaca anormal e doenca coronariana","fonte":"Estudo Cleveland Clinic","eixo":"fit-doencas","gene":"CHRM2","rsid":"rs324640","evidencia":"forte-fenotipo","texto":"A recuperacao anormal da frequencia cardiaca apos exercicio mantem-se preditiva de morte mesmo apos ajuste para gravidade angiografica da doenca arterial coronariana, funcao ventricular e capacidade de exercicio. Conecta o painel Fit (recuperacao cardiaca lenta) ao painel de doencas (doenca arterial coronariana), com a ressalva de que a evidencia e forte para o fenotipo e fraca para o elo genotipo-fenotipo via CHRM2."},
{"id":"cpic_slco1b1_sinvastatina","titulo":"Diretriz CPIC: SLCO1B1 e miopatia por sinvastatina","fonte":"CPIC Guideline (diretriz clinica formal)","eixo":"farma","gene":"SLCO1B1","rsid":"rs4149056","evidencia":"alta","texto":"A diretriz do Clinical Pharmacogenetics Implementation Consortium (CPIC) para SLCO1B1 e sinvastatina classifica como ALTA a evidencia que liga variantes de funcao reduzida do SLCO1B1 ao risco de miopatia induzida por sinvastatina. O alelo de risco e o C de rs4149056; o genotipo TT (sem o alelo C) indica funcao normal do transportador e menor risco de miopatia. Fonte de evidencia mais forte do corpus por ser diretriz clinica formal."},
{"id":"metformina_atm_gwas","titulo":"GWAS: ATM rs11212617 e resposta glicemica a metformina","fonte":"Nature Genetics (GWAS)","eixo":"farma","gene":"ATM","rsid":"rs11212617","evidencia":"moderada","texto":"Estudo de associacao genomica ampla identificou o locus ATM, variante rs11212617, associado ao sucesso do tratamento glicemico com metformina, com odds ratio de aproximadamente 1,35 para alcance da meta de controle glicemico. Ressalva importante: a associacao nao foi replicada de forma consistente em todos os estudos posteriores; o Diabetes Prevention Program (DPP) nao confirmou o efeito. Apresentar como associacao real porem menos consolidada que a de SLCO1B1."},
{"id":"metformina_atm_replicacao","titulo":"Replicacao do efeito de ATM na resposta a metformina","fonte":"Meta-analise de replicacao (multiplas coortes)","eixo":"farma","gene":"ATM","rsid":"rs11212617","evidencia":"moderada-inconsistente","texto":"Esforcos de replicacao do efeito do locus ATM (rs11212617) sobre a resposta a metformina produziram resultados mistos entre coortes. Reforca a necessidade de cautela: a associacao existe na literatura mas seu tamanho de efeito e replicabilidade sao incertos. A LLM deve declarar essa incerteza ao mencionar metformina/ATM."},
{"id":"farmacogenomica_brasil_scielo","titulo":"Farmacogenomica e diversidade da populacao brasileira","fonte":"Revisao SciELO","eixo":"contexto-brasil","gene":None,"rsid":None,"evidencia":"contexto","texto":"A populacao brasileira e uma das mais heterogeneas do mundo do ponto de vista genetico, resultado de intensa miscigenacao. Isso tem implicacoes importantes na interpretacao de ensaios farmacogeneticos e na extrapolacao de dados obtidos em outras populacoes, especialmente europeias. Fundamenta a declaracao de limitacao populacional: marcadores e pesos derivados majoritariamente de populacoes europeias tem transferibilidade reduzida para o contexto brasileiro."},
{"id":"prs_transferibilidade_fmrp","titulo":"Transferibilidade de escores de risco poligenico entre populacoes","fonte":"Material FMRP-USP","eixo":"contexto-brasil","gene":None,"rsid":None,"evidencia":"contexto","texto":"A capacidade preditiva de escores de risco poligenico (PRS) em populacoes nao europeias e menor, devido a diferencas de frequencia alelica e de desequilibrio de ligacao entre populacoes. Isso limita a aplicabilidade direta de PRS em populacoes geneticamente diversas como a brasileira. Sustenta, no nivel estatistico, a limitacao populacional do projeto."},
{"id":"cv_genes_proadi","titulo":"CV-Genes: esforco nacional para PRS cardiovascular brasileiro","fonte":"Projeto CV-Genes (PROADI-SUS)","eixo":"contexto-brasil","gene":None,"rsid":None,"evidencia":"contexto","texto":"O projeto CV-Genes, no ambito do PROADI-SUS, pretende derivar um escore de risco poligenico a partir da propria populacao do Brasil, algo inedito no pais, dado que escores desse tipo estao disponiveis majoritariamente para populacoes norte-americana, europeia ou asiatica. Demonstra que existe esforco nacional ativo para corrigir a lacuna de representatividade, fortalecendo o enquadramento do pitch."},
]

base = pathlib.Path("data/corpus")
base.mkdir(parents=True, exist_ok=True)
for c in corpus:
    (base / f"{c['id']}.json").write_text(json.dumps(c, ensure_ascii=True, indent=2), encoding="utf-8")
print(f"{len(corpus)} fontes escritas em data/corpus/")