services:
  backend:
    build:
      context: ../backend
    container_name: hackathon-amd-backend
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    
    volumes:
      - faiss_index:/app/data/faiss_index

  frontend:
    build:
      context: ../frontend
    container_name: hackathon-amd-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  faiss_index: